Simplify Hero and Scarecrow
palmdrop/BattleBoids pull request #70
Opened 2021-03-15 10:49 UTC by frans-bergman

2021-03-16 12:52 UTC, palmdrop requested changes
Looks okay but I had some thoughts regarding some of the changes. Left a few comments.

2021-03-16 12:52 UTC, palmdrop commented on Assets/Scripts/Boid/Boid.cs
> +
We should probably find a way to move this function to a burst job

2021-03-16 12:52 UTC, palmdrop commented on Assets/Scripts/Boid/BoidManager.cs
> +                    fearMultiplier = 10f;
Instead of using a magic number here, maybe the scarecrow itself could hold the fear multiplier?

2021-03-16 12:52 UTC, palmdrop commented on Assets/Scripts/Boid/BoidManager.cs
>                      boost++;
It seems like heroes still boost morale?

2021-03-16 12:52 UTC, palmdrop commented on Assets/Scripts/Boid/Hero.cs
> +            ally.GiveBoost(5f);
Let the hero have a field for the boost amount instead?

2021-03-16 12:52 UTC, palmdrop commented on Assets/Scripts/Boid/Melee.cs
> +            target.TakeDamage(IsBoosted() ? 5 * damage : damage);
Is this "5" the same as the boost amount applied by the hero? Should probably be a variable and not a magic number

2021-03-17 10:00 UTC, palmdrop approved these changes
Looks good, approved! However, left one small comment

2021-03-17 10:17 UTC, frans-bergman commented on Assets/Scripts/Boid/Healer.cs
> +        if (friendlyTarget == null
C# continues to amaze me...

2021-03-17 10:28 UTC, merged